export { Login } from "./Login";
export { default as Dashboard } from "./Dashboard";
export { default as Users } from "./Users";
export { default as Videos } from "./Videos";
export { default as Channels } from "./Channels";
export { default as Analytics } from "./Analytics";
export { default as Settings } from "./Settings";
export { Roles } from "./Roles";
export { UserDetail } from "./UserDetail";
export { UserVideos } from "./UserVideos";
export { UserActivity } from "./UserActivity";
export { UserSubscription } from "./UserSubscription";
export { Support } from "./Support";
export { Playlists } from "./Playlists";
export { PlaylistDetail } from "./PlaylistDetail";
export { Categories } from "./Categories";
export { SubscriptionPlans } from "./SubscriptionPlans";
export { ConfigSettings } from "./ConfigSettings";
export { Notifications } from "./Notifications";
export { Reports } from "./Reports";
export { Comments } from "./Comments";
export { Payments } from "./Payments";
export { PaymentGateways } from "./PaymentGateways";
export { Subscriptions } from "./Subscriptions";
export { Unauthorized } from "./Unauthorized";
export { AdminUsers } from "./AdminUsers";
export { default as Monetization } from "./Monetization";
export { default as AdPages } from "./AdPages";
export { default as AdSlots } from "./AdSlots";
export { default as AdBookings } from "./AdBookings";
